[book]
authors = ["Portable SIMD Members"]
language = "en"
multilingual = false
src = "."
title = "Portable SIMD Project Group"

[output.html]
no-section-label=true
git-repository-url="https://github.com/rust-lang/portable-simd"
